--- #YAML:1.0
name:                POE-Component-DBIx-MyServer
version:             0.01_03
abstract:            A pseudo mysql POE server
license:             perl
author:              
    - Eriam Schaffter <eriam@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Catalyst:                      0
    Class::Inspector:              0
    Module::Find:                  0.06
    Module::Reload:                0
    POE:                           0.38
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
